### ISSUE TITLE
Can't open .exe file

### ISSUE THREAD

**Issue by Seitentaisei** [hadeutscher/OvercookedTool#1]
Not sure if I'm not  doing it correctly. I have .net framework. Nothing happens when I open the exe file though.

**Comment by hadeutscher** [comment]
It's a command line program (see README for instructions)

**Comment by uxduck** [comment]
It's missing instructions and assumes one is familiar with dotnet. I am not, but managed to figure it. Here's the rough steps I took:

Some steps you need to do:
- clone the repo
- install dotnet cli
- Download and install Dotnet **SDK** 3.1 (not just dotnet core). Don't use Dotnet 3.5, the syntax has changed and isn't compatible with this code.
  - Might not be required if dotnet cli will autodownload the SDK. Not sure.
- Run `dotnet build` to generate the executable (.exe)
- Use the executable file (it is generated in `bin/Debug/netcoreapp3.1`) to decrypt original save files (with old username) - you can download 100% completion save files on the internet
- Use the executable file to encrypt to new save files (with new username)

It works, but takes a few minutes once you know all the steps. It will probably take some skill to avoid making mistakes and adding some detail to these steps I didn't have time to write.
