### ISSUE TITLE
Conversion from Steam to Epic makes new save instead of converting

### ISSUE THREAD

**Issue by Captain2137** [hadeutscher/OvercookedTool#10]

**Comment by weihan444** [comment]
What do you mean by making new save, can you provide description on that? If you mean the tool creating a new copy of the save with different encryption, then it is supposed to do that.

**Comment by Captain2137** [comment]
What I mean is the save it converts from steam to epic has zero progress on it when opened by the epic version. I got a lot of progress done on my steam one, but since they shutdown cross play, I tried to convert my save over to epic so I could play coop, but the save is just empty like a newly created save. Perhaps it is a DLC issue since I own more DLC on steam than epic?

**Comment by weihan444** [comment]
Did you also convert the other file inside the save file like CoopSlot_SaveFile_0.save besides Meta_SaveFile.save. Since those are also necessary for the save to work.

**Comment by Captain2137** [comment]
I did that and now it works, thanks. Someone should probably update the readme file with this info.
