### ISSUE TITLE
Unable to understand some steps, needed to proceed the use of application

### ISSUE THREAD

**Issue by EdwardRandger** [hadeutscher/OvercookedTool#11]
I saw three issue titles in this thread (marked as fixed), but none of them could tell me properly, what I am doing wrong. After downloading .zip (as I understand, I need to do it) from this button I have some problems:
![image](https://user-images.githubusercontent.com/55622035/123064048-9b9c1a80-d416-11eb-8413-f4fdc470ac67.png)

I didn't find, which part of this archive I need to convert to .exe (didn't find it either in ReadMe, or here--> https://www.gog.com/forum/overcooked/transfer_steam_saves_to_gog in the message from trifouille), so I tried both converting all archive to exe (by simply renaming it to .exe and by many programs - but they were useless):
![image](https://user-images.githubusercontent.com/55622035/123064840-4e6c7880-d417-11eb-8c83-9b25807b9557.png)
, and converting only folder "OvercookedTool":
![image](https://user-images.githubusercontent.com/55622035/123064993-6cd27400-d417-11eb-83c1-751b6ab5b2fe.png)

But in both ways I had a problem while executing .exe:
![image](https://user-images.githubusercontent.com/55622035/123065136-8ffd2380-d417-11eb-8400-20da5c0b480d.png)
(it says: "Unsupported 16-bit application. The program or feature \??\C:\Users\Eduard\Downloads\OvercookedTool-master\OvercookedTool.exe failed to start due to incompatibility with 64-bit Windows.  Check with the software developer for a version of the program that is compatible with 64-bit Windows.")

Can you, please, help me finding out, how should I properly deal with this problem, or what I am doing wrong? Maybe there is a way to convert files to .exe in the right way, that i didn't know, or something else?

**Comment by weihan444** [comment]
the download zip button is for source code, meaning they are not compiled to run yet. For the compiled version, check the release tab here [https://github.com/hadeutscher/OvercookedTool/releases/tag/1.0](url) and download the OvercookedTool.exe which is ready to run. 
![image](https://user-images.githubusercontent.com/53114755/123092041-a1b4ea00-d45c-11eb-8d14-fd8e4ff16dcb.png)

**Comment by EdwardRandger** [comment]
> the download zip button is for source code, meaning they are not compiled to run yet. For the compiled version, check the release tab here [https://github.com/hadeutscher/OvercookedTool/releases/tag/1.0](url) and download the OvercookedTool.zip which is ready to run.
> ![image](https://user-images.githubusercontent.com/53114755/123092041-a1b4ea00-d45c-11eb-8d14-fd8e4ff16dcb.png)

Thank you for the explanation! This helped).
