### ISSUE TITLE
The savegame decryption password for Epic game stroe is not correct!

### ISSUE THREAD

**Issue by adokklu** [hadeutscher/OvercookedTool#16]
I am trying to transfer the epic game store savefile to stream.

According to the instruction,  the savegame password for encryption and decryption is "Epic.OnlineServices.EpicAccountId" without the quote. What is the "EpicAccountId" exactly? I have tried the folder name where the game save file is located and the ID which can be found in the Epic store account details. Both did not work and the error says:

Decryption failed
Wrong key?
<img width="660" alt="error" src="https://user-images.githubusercontent.com/15357749/147844681-28d6479d-8da5-4176-8c24-59fa635d7837.PNG">

I have tried the encryption and decryption for stream save file and it works fine.

**Comment by hadeutscher** [comment]
Might have to ask @weihan444 because he's the one who aded it, but I'm pretty sure he meant that the password is literally `Epic.OnlineServices.EpicAccountId`, without substituting anything.

**Comment by weihan444** [comment]
yes, it is literally Epic.OnlineServices.EpicAccountId without substituting anything

**Comment by adokklu** [comment]
Thanks a lot! Seems that I have misunderstood the instruction.
