### ISSUE TITLE
Overcooked Tool not working

### ISSUE THREAD

**Issue by Lego1210** [hadeutscher/OvercookedTool#19]
I am trying to convert my Overcooked 2 data from Epic games to my Overcooked all you can eat on steam but it's not working. I can see that it made the .json files but it wont replace the files on overcooked all you can eat. i can send what ever information you need in order to help me

**Comment by hadeutscher** [comment]
Hi,
This is for transferring saves between different editions of the game "Overcooked 2", "Overcooked: All You Can Eat" is a different game. I don't know if transferring saves between those games is possible, but definitely not with this tool.
