### ISSUE TITLE
GOG Migration with Offline Mode

### ISSUE THREAD

**Issue by LinnielDW** [hadeutscher/OvercookedTool#3]
Tool cannot migrate from GOG to steam if you save while played it in offline mode.

I decompiled the overcooked2 source code and had a look around. It uses SystemInfo.deviceUniqueIdentifier as the encryption pw if it cannot find it. I created a local unity project to find out what mine was, but this can be automated.

Proposal to decrypt file using SystemInfo.deviceUniqueIdentifier if argument not found.

**Comment by hadeutscher** [comment]
Are you sure it doesn't appear in the savegame path in AppData similar to Steam/GOG ID? How big of a deal is it to link against Unity SDK (like, is this a Nuget package or do you need to install it separately)?

**Comment by LinnielDW** [comment]
Instead of the path \Overcooked2\<GOG_ID>\*.save I found mine was saved in \Overcooked2\*.save. At work right now so I can't give you the exact method call, but from what I saw of the decompiled source, this happens when the userInstance.signedIn != true. I don't know how this happened. Was just trying to get migrate my gf's save file after I picking up OC2 gourmet edition on steam due to the sale.

SystemInfo is part of the UnityEngine package but when I tried running it from VS using the Unity Nuget package I got an ECalls forbidden error. Didn't take a look further into it, figured I missed some kind of config. So I just booted up Unity and ran the same method from there in a blank scene.

**Comment by hadeutscher** [comment]
well, if it doesn't link smoothely I'd rather have it as a different tool, do you wanna create one and I'll link it from the readme?

**Comment by LinnielDW** [comment]
Sure thing. Threw together a little applet, repo here:
https://github.com/LinnielDW/UnityDeviceUniqueIdentifierHarness

**Comment by hadeutscher** [comment]
👍
