### ISSUE TITLE
Error trying to run the .exe

### ISSUE THREAD

**Issue by HiagoPereira** [hadeutscher/OvercookedTool#4]
![image](https://user-images.githubusercontent.com/13768565/98725089-75d47080-2373-11eb-9b31-4832506a2a47.png)

Hey, I'm getting this error message whenever I try to run OvercookedTool.exe. I'm actually trying to convert a Steam Save File to another Steam Account and I'm getting this error. Can you guys help me? pls

**Comment by hadeutscher** [comment]
Read [the README](https://github.com/hadeutscher/OvercookedTool/blob/master/README.md)
