### ISSUE TITLE
Fails to launch exe. 

### ISSUE THREAD

**Issue by DansVox** [hadeutscher/OvercookedTool#6]
I get an unhandled exception error when trying to start the exe within cmd prompt. 

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OvercookedPasten.Program.Main(String[] args) in D:\Data\Projects\OvercookedTool\OvercookedTool\Program.cs:line 274

Any ideas? I've installed the dotnet as required.

**Comment by DansVox** [comment]
I worked it out, I was being stupid.

**Comment by sprollmm** [comment]
> I worked it out, I was being stupid.

I'm also experiencing the same exception. Could you please tell me how you resolved it?
