### ISSUE TITLE
Epic Games Overcooked 2 Decryption and Encryption

### ISSUE THREAD

**Issue by weihan444** [hadeutscher/OvercookedTool#7]
First, I apologize if this is not an issue.

I have wanted to transfer my save from Steam to Epic Games version of Overcooked 2. The ID of the folder cannot be used to decrypt the save file. It took me 4 hours to find the exact decryption ID of the save file and that is "Epic.OnlineServices.EpicAccountId" without the quote. I found it by modifying the Assembly-CSharp.dll(Thanks to the Xbox Game Pass issue post for pointing out the exact location) and makes the GetUniqueID method write the ID to a text file whenever the game starts.

I hope you can include this into your post, so it can help more people who wanted to do the same. Thank you for making this tool too.

**Comment by hadeutscher** [comment]
Sure, if you want you can add this to the README file and open a PR
