### ISSUE TITLE
Disambiguated requirements

### ISSUE THREAD

**Issue by Bigstool** [hadeutscher/OvercookedTool#9]
It seems to me that the required environment was not .NET Framework but [.NET Runtime 3.1.16](https://dotnet.microsoft.com/download/dotnet/3.1), which took me a while to figure out after running into errors trying to run the tool with .NET Framework 4.8 and .NET Runtime 5.0.7 installed.

Would you consider making the requirements more specific so that we can locate the required environment faster?

**Comment by hadeutscher** [comment]
Feel free to edit the README with details, links, etc.
